spring:
  application:
    name: springboot-blog-rest-api
  datasource:
    url: jdbc:mysql://localhost:3306/myblog
    username: root
    password: root

  jpa:
    hibernate:
        ddl-auto: update
    show-sql: true